name: Push env variables

on:
  workflow_dispatch:

jobs:
  env:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ciss298.zenren.xyz
          username: deployuser
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/ciss298-TeamProject
            chmod -R 755 .
            echo "DB_HOST=localhost" > .env
            echo "DB_USER=root" >> .env
            echo "DB_PASS=${{ secrets.DB_PASS }}" >> .env
            echo "DB_NAME=hotel" >> .env
